---
- name: Add NGINX repository (7.x)
  yum_repository:
    name: nginx
    description: NGINX YUM repo
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
  vars:
    ansible_python_interpreter: /usr/bin/python
  become: yes
  become_method: sudo

- name: Install nginx
  yum:
    name: nginx
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python
  become: yes
  become_method: sudo

- name: Ensure default web directory exists
  file:
    path: /nfs/web/default
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  become: yes
  become_method: sudo

- name: Replace nginx default configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  become: yes
  become_method: sudo

- name: Copy nginx custom configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: yes
  become_method: sudo

- name: Start nginx Service
  command: systemctl start nginx.service
  become: yes
  become_method: sudo
