---
- name: Cleanup CentOS VMs
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Delete VM
      vmware_guest:
        hostname: "{{ vm_vsphere_host }}"
        username: "{{ vm_vsphere_user }}"
        password: "{{ vm_vsphere_password }}"
        validate_certs: no
        name: "{{ inventory_hostname }}"
        state: "absent"
        force: yes
