---
#  - name: Fetch random salts for WordPress config
#    local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
#    register: wp_salt
#    when: "'wp01' in inventory_hostname"

  - name: Copy WordPress config file
    template: src=wp-config.php dest={{ wp_path }} owner=wordpress group=wordpress
    become: yes
    become_method: sudo
    when: "'wp01' in inventory_hostname"

  - name: Set WP configuration
    shell: >
      curl --header "Host: {{ wp_hostname }}"
      --data-urlencode "weblog_title=ZT Demo Portal"
      --data-urlencode "user_name={{ wp_admin_name }}"
      --data-urlencode "admin_email={{ wp_admin_email }}"
      --data-urlencode "admin_password={{ wp_admin_password }}"
      --data-urlencode "admin_password2={{ wp_admin_password }}"
      --data-urlencode "pw_weak=1" "http://localhost/wp-admin/install.php?step=2"
    when: "'wp01' in inventory_hostname"
    ignore_errors: True
    tags:
      - wp-config
    args:
      warn: false

  - name: Set selinux to permissive
    shell: "setenforce 0"
    become: yes
    become_method: sudo
