---
  - name: Is WordPress downloaded?
    stat: path="{{ www_root }}/wordpress/index.php"
    register: wp_dir
    #wp_dir.stat.isdir is not defined

  - name: Update hosts files for wordpress
    lineinfile:
      dest: /etc/hosts
      line: '127.0.0.1 {{ wp_hostname }}'
      owner: root
      group: root
      mode: 0644
    become: yes
    become_method: sudo

  - name: Download WordPress
    get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/tmp/wordpress-{{ wp_version }}.tar.gz
 #            sha256sum="{{ wp_sha256sum }}"
    when: "'wp01' in inventory_hostname"

  - name: Extract archive
    unarchive:
      src: /tmp/wordpress-{{ wp_version }}.tar.gz
      dest: "{{ www_root }}"
      remote_src: true
    become: yes
    become_method: sudo
    when: "'wp01' in inventory_hostname"

  - name: Add group "wordpress"
    group: name=wordpress
    become: yes
    become_method: sudo

  - name: Add user "wordpress"
    user: name=wordpress group=wordpress home="{{ wp_path }}"
    become: yes
    become_method: sudo

  - name: Change ownership of WordPress installation
    file: path="{{ wp_path }}" owner=wordpress group=wordpress state=directory recurse=yes
    become: yes
    become_method: sudo
    when: "'wp01' in inventory_hostname"
