---
- name: Install NFS Client packages
  yum:
    name: nfs-utils
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python
  become: yes
  become_method: sudo

- name: Configure NFS (avoid dynamic ports)
  template:
    src: nfs.j2
    dest: /etc/sysconfig/nfs
    mode: 0644
  become: yes
  become_method: sudo

- name: Ensure rpcbind is running.
  service:
    name: rpcbind
    state: restarted
    enabled: yes
  become: yes
  become_method: sudo

- name: Create mountable dir
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: root
    group: root
  with_items: "{{ nfs_mount }}"
  become: yes
  become_method: sudo

- name: set mountpoints
  mount:
    path: "{{ item }}"
    src: "{{ nfs_server }}:{{ item }}"
    fstype: nfs
    opts: auto,noatime,nolock
    state: mounted
  with_items: "{{ nfs_mount }}"
  become: yes
  become_method: sudo
